from .circulo import Circulo
from .linha import Linha
from .oval import Oval
from .rabisco import Rabisco
from .retangulo import Retangulo
from .quadrado import Quadrado
from .borracha import Borracha
from .poligono import Poligono
from .figuras import Figuras
from .triangulo_reto import Triangulo_Reto